### ISSUE TITLE
question: how to adjust icon size?

### ISSUE THREAD

**Issue by AimPizza** [ponas-niekas/waybar-timer#1]
After adding the custom module (which is pretty neat btw), the waybar logs are telling me that it needs a height of at least 48:

`[2024-05-24 09:28:17.488] [warning] Requested height: 40 is less than the minimum height: 48 required by the modules`

I'm not sure where or how to specify the icon of the timer to be smaller. I've tried reducing the font-size in the css file but it still requires 48 px which is a bit much considering the otherwise small text

```css
* {
  border: none;
  border-radius: 0;
  min-height: 0;
  font-family: JetBrainsMono Nerd Font;
  /* font-size: 10px; */
  font-size: 8px;
}
```
